src/objects/RecallDataSource__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Recall Info data source configuration and external URL</description>
    <fields>
        <fullName>DataHubURL__c</fullName>
        <defaultValue>&quot;http://evening-beach-9369.herokuapp.com/podracer/&quot;</defaultValue>
        <description>A URL end-point for the REST service providing Recall data</description>
        <inlineHelpText>A URL end-point for the REST service providing Recall data</inlineHelpText>
        <label>DataHubURL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>RecallDataSource</label>
</CustomObject>

src/classes/PodracerUpdater.cls
global class PodracerUpdater {

  @future (callout=true)
  public static void sendUpdate(String externalId, String updateBody) {
    RecallDataSource__c rds = RecallDataSource__c.getOrgDefaults();
 
    String podracerModelEncoded = EncodingUtil.urlEncode(externalId, 'UTF-8');

    HttpRequest req = new HttpRequest();
    req.setMethod('PUT');
    req.setEndpoint(rds.dataHubURL__c + externalId);
    req.setBody(updateBody);
    Http http = new Http();
    HTTPResponse res = http.send(req);
  }
  
}